language: ruby
cache: bundler
rvm:
  - 2.0.0-p247
before_script:
  - psql -c "CREATE USER ideesbebe WITH PASSWORD 'sefsef';" -U postgres
  - psql -c 'CREATE DATABASE ideesbebe_test OWNER ideesbebe;' -U postgres
script: RAILS_ENV=test bundle exec rake db:reset && bundle exec rspec spec