language: ruby
rvm:
  - 2.0.0-p247
env:
  - DB=postgresql
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
before_script:
  - psql -c "CREATE USER ideesbebe WITH PASSWORD 'sefsef';" -U postgres
  - psql -c 'CREATE DATABASE ideesbebe_test;' -U postgres
bundler_args: --binstubs=./bundler_stubs