language: ruby
rvm:
  - 2.0.0-p247
env:
  - DB=postgresql
  - CODECLIMATE_REPO_TOKEN=8f55070ed36065d5f547d3d3d2f21f63ac7138fe7300997cf456379720bb0991 
script: 
  - RAILS_ENV=test bundle exec rake db:migrate && bundle exec rspec spec
before_script:
  - psql -c "CREATE USER ideesbebe WITH PASSWORD 'sefsef';" -U postgres
  - psql -c 'CREATE DATABASE ideesbebe_test OWNER ideesbebe;' -U postgres
